cd ${VMCWORKDIR}\/macros

RECOFILE=$1
OUTPUT=$2
NEXTJOB=$3
CONFIGLIST=$4
MCFILE=$5
DESTINATION=$6
FISHTANKUSER=$7
CONFIGFILE=$8
MCSUBMITFILE=$9

# Creat directory for logging 
#echo ${MCSUBMITFILE} ${OUTPUT} ${CONFIGLIST} ${CONFIGFILE}
MCID=$(sbatch ${MCSUBMITFILE} ${OUTPUT} ${CONFIGLIST} ${CONFIGFILE})
MCID=$(echo $MCID | awk '{print $NF}')
sbatch --dependency=afterok:${MCID} ${RECOFILE} ${OUTPUT} ${NEXTJOB} ${CONFIGLIST} ${MCFILE} ${DESTINATION} ${FISHTANKUSER}

