#root -b -q EventSelection/MomCorrection.C\(false,1,true,false,false\) > Log1 &
#root -b -q EventSelection/MomCorrection.C\(false,2,true,false,false\) > Log2 &
#root -b -q EventSelection/MomCorrection.C\(false,3,true,false,false\) > Log3 &
root -b -q EventSelection/NewEfficiency.C\(false,3,false,false,false\) > Log3EF &
#root -b -q EventSelection/MomCorrection.C\(false,10,true,false,false\) > Log10 &
#root -b -q EventSelection/MomCorrection.C\(true,1,true,false,false\) > Logva1 &
#root -b -q EventSelection/MomCorrection.C\(true,2,true,false,false\) > Logva2 &
#root -b -q EventSelection/MomCorrection.C\(true,3,true,false,false\) > Logva3 &
#root -b -q EventSelection/NewEfficiency.C\(true,3,false,false,false\) > Logva3EF &
#root -b -q EventSelection/MomCorrection.C\(true,10,true,false,false\) > Logva10 &
